# Generated by Django 5.0.3 on 2024-05-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0002_utilisateur_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaisonDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
