# Generated by Django 5.0.3 on 2024-05-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0003_maisondisponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maisondisponible',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='maisondisponible',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
