# Generated by Django 5.0.3 on 2024-05-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0005_alter_maisondisponible_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maisondisponible',
            name='latitude',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='maisondisponible',
            name='longitude',
            field=models.CharField(max_length=30),
        ),
    ]
