# Generated by Django 5.0.3 on 2024-05-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0006_alter_maisondisponible_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maisondisponible',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EasyHouse.property'),
            preserve_default=False,
        ),
    ]
