# Generated by Django 5.0.3 on 2024-05-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0008_image_remove_property_photos_property_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photos',
        ),
        migrations.AddField(
            model_name='image',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='EasyHouse.property'),
            preserve_default=False,
        ),
    ]
