# Generated by Django 5.0.3 on 2024-05-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0011_categorieimage_image_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='CategorieImage',
        ),
    ]
