# Generated by Django 5.0.3 on 2024-05-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0012_remove_image_categorie_delete_categorieimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='terrasse',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='prix',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('maison', 'Appartement mensuel'), ('appartement', 'Appartement journaliser')], max_length=255),
        ),
    ]
