# Generated by Django 5.0.3 on 2024-05-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0013_property_terrasse_alter_property_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=25),
        ),
    ]
