# Generated by Django 5.0.3 on 2024-05-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0014_property_parking_property_wifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='superficie_interne',
            field=models.IntegerField(default=0),
        ),
    ]
