# Generated by Django 5.0.3 on 2024-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0015_property_superficie_interne'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='nombre_de_salons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='nombre_de_chambres',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='nombre_de_toilettes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
