# Generated by Django 5.0.3 on 2024-05-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0016_property_nombre_de_salons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Appartement mensuel', 'Appartement mensuel'), ('Appartement journalier', 'Appartement journalier'), ('Appartement hebdomadaire', 'Appartement hebdomadaire')], max_length=255),
        ),
    ]
