# Generated by Django 5.0.3 on 2024-05-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0017_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
