# Generated by Django 5.0.3 on 2024-06-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0020_rental_delete_rentalrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='adresse',
            new_name='adresse_email',
        ),
    ]
