# Generated by Django 5.0.3 on 2024-06-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0021_rename_adresse_rental_adresse_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('adresse_email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('date_visit', models.DateField()),
                ('heure_heure', models.TimeField()),
            ],
        ),
    ]
