# Generated by Django 5.0.3 on 2024-06-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0023_rename_heure_heure_visit_heure_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date_visit',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='heure_visit',
            field=models.TimeField(blank=True),
        ),
    ]
