# Generated by Django 5.0.3 on 2024-06-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0024_alter_visit_date_visit_alter_visit_heure_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
