# Generated by Django 5.0.3 on 2024-06-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0032_property_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='property',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Achat',
        ),
        migrations.DeleteModel(
            name='Avis',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
