# Generated by Django 5.0.3 on 2024-06-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyHouse', '0036_contact_objet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Easy Day', 'Easy Day'), ('Easy Month', 'Easy Month')], max_length=255),
        ),
    ]
